name: Build KMonad

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version tag to build.
        required: true

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: kmonad/kmonad
        ref: ${{ inputs.version }}

    - name: Install Scoop
      shell: pwsh
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install stack

    - name: Compile KMonad
      run: |
        stack build

    - name: Install KMonad
      run: |
        stack install

    - name: Set APPDATA
      run: echo ("APPDATA_DIR=" + $env:APPDATA) >> $env:GITHUB_ENV

    - name: Upload KMonad artifact
      uses: actions/upload-artifact@v3
      with:
        name: kmonad-executable
        path: ${{ env.APPDATA_DIR }}\local\bin\

    - name: Upload KMonad release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        make_latest: true
        files: ${{ env.APPDATA_DIR }}\local\bin\kmonad.exe
