name: Build KMonad

on:
  push:
    branches: ['build']
  schedule:
      - cron: '0 12 1 */6 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: kmonad/kmonad

    - name: Install Scoop
      shell: pwsh
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install stack

    - name: Compile KMonad
      run: |
        stack build

    - name: Install KMonad
      run: |
        stack install

    - name: Set APPDATA
      run: echo ("APPDATA_DIR=" + $env:APPDATA) >> $env:GITHUB_ENV

    - name: Upload KMonad artifact
      uses: actions/upload-artifact@v3
      with:
        name: kmonad-executable
        path: ${{ env.APPDATA_DIR }}\local\bin\
